# Generated by Django 5.0.1 on 2026-01-05 13:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('open', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('high', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('low', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('close', models.DecimalField(decimal_places=4, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('volume', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('adjusted_close', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(db_index=True, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ratio', models.CharField(max_length=20)),
                ('split_from', models.IntegerField()),
                ('split_to', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='StockCache',
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='research_st_symbol_8b4e89_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['sector', 'industry'], name='research_st_sector_639119_idx'),
        ),
        migrations.AddField(
            model_name='historicalprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical_prices', to='research.stock'),
        ),
        migrations.AddField(
            model_name='dividend',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='research.stock'),
        ),
        migrations.AddField(
            model_name='stocksplit',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='research.stock'),
        ),
        migrations.AddIndex(
            model_name='historicalprice',
            index=models.Index(fields=['stock', '-date'], name='research_hi_stock_i_0b3f07_idx'),
        ),
        migrations.AddIndex(
            model_name='historicalprice',
            index=models.Index(fields=['date'], name='research_hi_date_1fdfda_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='historicalprice',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='dividend',
            index=models.Index(fields=['stock', '-date'], name='research_di_stock_i_fc298b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dividend',
            unique_together={('stock', 'date')},
        ),
        migrations.AddIndex(
            model_name='stocksplit',
            index=models.Index(fields=['stock', '-date'], name='research_st_stock_i_b96169_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stocksplit',
            unique_together={('stock', 'date')},
        ),
    ]
