# Generated by Django 5.0.1 on 2026-02-10 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_userregistrationrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='financial_metrics', serialize=False, to='research.stock')),
                ('trailing_pe', models.DecimalField(blank=True, decimal_places=2, help_text='Trailing 12-month Price-to-Earnings ratio', max_digits=10, null=True)),
                ('forward_pe', models.DecimalField(blank=True, decimal_places=2, help_text='Forward Price-to-Earnings ratio', max_digits=10, null=True)),
                ('payout_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Dividend payout ratio as percentage (0-100)', max_digits=5, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Current dividend yield as percentage', max_digits=5, null=True)),
                ('dividend_growth_1y', models.DecimalField(blank=True, decimal_places=2, help_text='1-year dividend growth rate as percentage', max_digits=8, null=True)),
                ('dividend_growth_5y', models.DecimalField(blank=True, decimal_places=2, help_text='5-year dividend growth CAGR as percentage', max_digits=8, null=True)),
                ('chowder_number', models.DecimalField(blank=True, decimal_places=2, help_text='Chowder Number: Dividend Yield + 5Y Dividend Growth', max_digits=8, null=True)),
                ('pays_dividend', models.BooleanField(default=False, help_text='Whether the stock pays dividends')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Financial Metrics',
                'verbose_name_plural': 'Financial Metrics',
                'indexes': [models.Index(fields=['pays_dividend'], name='research_fi_pays_di_507888_idx'), models.Index(fields=['last_updated'], name='research_fi_last_up_0324a4_idx')],
            },
        ),
    ]
