# Generated by Django 5.0.1 on 2026-02-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_financialmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmetrics',
            name='fcf_payout_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='FCF payout ratio: Dividends / Free Cash Flow as percentage', max_digits=5, null=True),
        ),
    ]
