# Generated by Django 5.0.1 on 2026-07-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0010_financialmetrics_dividend_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
