# Generated by Django 5.0.1 on 2026-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0011_dividend_declaration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='declaration_date_checked',
            field=models.BooleanField(default=False),
        ),
    ]
