# Generated by Django 5.0.1 on 2026-07-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0012_dividend_declaration_date_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_etf',
            field=models.BooleanField(default=False),
        ),
    ]
