# Generated by Django 5.0.1 on 2026-07-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0013_stock_is_etf'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='entity_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('MLP', 'MLP'), ('REIT', 'REIT')], default='REGULAR', max_length=10),
        ),
    ]
