# Generated by Django 5.0.1 on 2026-09-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0014_stock_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialmetrics',
            name='fcf',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Trailing twelve months Free Cash Flow, in the stock's native currency", max_digits=20, null=True),
        ),
    ]
