# Generated by Django 5.0.1 on 2026-06-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_transaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIV', 'Dividend'), ('SPOF', 'Spin-Off'), ('INT', 'Interest'), ('DEP', 'Deposit'), ('WIT', 'Withdrawal'), ('EXC', 'Exchange')], max_length=8),
        ),
    ]
