# Generated by Django 5.0.1 on 2026-07-04 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_fx_currency_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Expected withholding tax at source, computed from the portfolio owner's TaxWithholdingRule at creation time — always editable afterward.", max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax withheld at source on this transaction (e.g. dividend/interest withholding tax)', max_digits=10),
        ),
        migrations.CreateModel(
            name='TaxWithholdingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('entity_type', models.CharField(choices=[('REGULAR', 'Regular'), ('MLP', 'MLP'), ('REIT', 'REIT')], default='REGULAR', max_length=10)),
                ('symbol', models.CharField(blank=True, help_text='If set, overrides the country/entity_type rule for this specific stock only', max_length=10, null=True)),
                ('withholding_tax_rate', models.DecimalField(decimal_places=2, help_text='Percentage withheld at source, e.g. 15.00 for 15%', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_withholding_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['country', 'entity_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='taxwithholdingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol__isnull', False)), fields=('user', 'symbol'), name='unique_user_symbol_tax_rule'),
        ),
        migrations.AddConstraint(
            model_name='taxwithholdingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('symbol__isnull', True)), fields=('user', 'country', 'entity_type'), name='unique_user_country_entity_tax_rule'),
        ),
    ]
