# Generated by Django 5.0.1 on 2026-07-08 21:52

from django.db import migrations, models


def backfill_is_manual(apps, schema_editor):
    """
    Before this field existed, notes == 'Auto-recorded' was the only signal
    distinguishing sync-created rows from anything else. Preserve that as the
    starting point for is_manual so no pre-existing row's sync eligibility
    changes as a side effect of this migration.
    """
    Dividend = apps.get_model('portfolio', 'Dividend')
    Dividend.objects.exclude(notes='Auto-recorded').update(is_manual=True)


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_dividend_tax_transaction_tax_taxwithholdingrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dividend',
            name='is_manual',
            field=models.BooleanField(default=False, help_text='True once a user has manually created or edited this record — auto_record_dividends recomputes/deletes non-manual rows on every sync but never touches manual ones.'),
        ),
        migrations.RunPython(backfill_is_manual, migrations.RunPython.noop),
    ]
