# Generated by Django 5.0.1 on 2026-08-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_dividend_is_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIV', 'Dividend'), ('SPOF', 'Spin-Off'), ('INT', 'Interest'), ('DEP', 'Deposit'), ('WIT', 'Withdrawal'), ('EXC', 'Exchange'), ('OPT_PAID', 'Option Premium Paid'), ('OPT_REC', 'Option Premium Received')], max_length=8),
        ),
    ]
